# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-03 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal.models
import journal.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(help_text='Represents the abstract of the paper.', max_length=2000)),
                ('authors', models.TextField(help_text='Each row represents an author that follows this template: (First Name, Last Name, Email, Affiliation, Country, Corresponding Author)', max_length=4096)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('under_review', 'Under Review'), ('preliminary_reject', 'Preliminary Reject'), ('accepted', 'Accepted')], default='processing', max_length=64)),
                ('manuscript', models.FileField(upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'), max_size=52428800)])),
                ('cover_letter', models.FileField(upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'), max_size=52428800)])),
                ('supplementary_materials', models.FileField(blank=True, default=None, null=True, upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'), max_size=52428800)])),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_papers', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('editor_review', models.BooleanField()),
                ('appropriate', models.CharField(choices=[('appropriate', 'The topic of this manuscript falls within the scope of the journal.'), ('not_appropriate', 'The topic of this manuscript does not fall within the scope of the journal.')], default=None, max_length=64)),
                ('recommendation', models.CharField(choices=[('0', 'Consider after Major Changes.'), ('+2', 'Publish Unaltered.'), ('+1', 'Consider after Minor Changes.'), ('-1', 'Reject. (Paper is not of sufficient quality or novelty to be published in this journal)'), ('-2', 'Reject. (Paper is seriously flawed; Do not encourage resubmission)')], default=None, max_length=64)),
                ('comment', models.TextField(help_text='This comment will be shown to the author.', max_length=32768)),
                ('confidential_comment', models.TextField(help_text='This comment will not be shown to the author.', max_length=32768)),
                ('additional_file', models.FileField(blank=True, upload_to=journal.models.review_user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'), max_size=52428800)])),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='journal.Paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
