# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import journal.models
import journal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20170703_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='file',
        ),
        migrations.AddField(
            model_name='paper',
            name='cover_letter',
            field=models.FileField(default='Asd', upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'text/plain'), max_size=52428800)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='manuscript',
            field=models.FileField(default='asd', upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'text/plain'), max_size=52428800)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='supplementary_materials',
            field=models.FileField(default=None, null=True, upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'text/plain'), max_size=52428800)]),
        ),
    ]
