# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import journal.models
import journal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_paper_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='paper',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('under_review', 'Under Review'), ('preliminary_reject', 'Preliminary Reject'), ('accepted', 'Accepted')], default='processing', max_length=64),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cover_letter',
            field=models.FileField(upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'), max_size=52428800)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='manuscript',
            field=models.FileField(upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'), max_size=52428800)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='supplementary_materials',
            field=models.FileField(blank=True, default=None, null=True, upload_to=journal.models.user_id_path, validators=[journal.validators.FileValidator(content_types=('application/pdf', 'text/html', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'), max_size=52428800)]),
        ),
    ]
