# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20170705_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.TextField(help_text='Each row represents an author that follows this template: (First Name, Last Name, Email, Affiliation, Country, Corresponding Author)', max_length=4096),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(help_text='Represents the abstract of the paper.', max_length=2000),
        ),
    ]
