# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20170710_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appropriate',
            field=models.CharField(choices=[('appropriate', 'The topic of this manuscript falls within the scope of the journal.'), ('not_appropriate', 'The topic of this manuscript does not fall within the scope of the journal.')], default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='This comment will be shown to the author.', max_length=32768),
        ),
        migrations.AlterField(
            model_name='review',
            name='confidential_comment',
            field=models.TextField(help_text='This comment will not be shown to the author.', max_length=32768),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(choices=[('0', 'Consider after Major Changes.'), ('+2', 'Publish Unaltered.'), ('+1', 'Consider after Minor Changes.'), ('-1', 'Reject. (Paper is not of sufficient quality or novelty to be published in this journal)'), ('-2', 'Reject. (Paper is seriously flawed; Do not encourage resubmission)')], default=None, max_length=64),
        ),
    ]
