# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20170711_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='editor_review',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
