# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20170718_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
