# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_inivtation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('accepted', models.NullBooleanField()),
                ('login_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.LoginToken')),
            ],
        ),
        migrations.RemoveField(
            model_name='inivtation',
            name='login_token',
        ),
        migrations.DeleteModel(
            name='Inivtation',
        ),
    ]
