# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='B9B61JoItOT5FQ', max_length=64),
        ),
    ]
